<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>EidoGo - Go Games, Pattern Search, Joseki Tutor, SGF Editor</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="site-style.css">
<link media="only screen and (max-device-width: 480px)" href="site-style-iphone.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" href="player/player.css">
<!--[if IE 6]>
<link rel="stylesheet" href="player/player-ie6.css">
<![endif]-->
<meta name="viewport" content="width=421, minimum-scale=0.76">
<link media="only screen and (max-device-width: 480px)" href="player/player-iphone.css" type="text/css" rel="stylesheet">
<!--
    For international support, uncomment the following line and put in the
    appropriate language code (see the 'player/i18n' folder).
-->
<!-- <script type="text/javascript" src="player/i18n/pt_br.js"></script> -->

<script type="text/javascript" src="player/player.compressed.js"></script>

<!--
    Uncomment the following to work with the original source.
-->
<!-- <script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.dimensions.js"></script>
<script type="text/javascript" src="js/jquery.history.js"></script>
<script type="text/javascript" src="js/lang.js"></script>
<script type="text/javascript" src="js/eidogo.js"></script>
<script type="text/javascript" src="js/util.js"></script>
<script type="text/javascript" src="js/i18n.js"></script>
<script type="text/javascript" src="js/gametree.js"></script>
<script type="text/javascript" src="js/sgf.js"></script>
<script type="text/javascript" src="js/board.js"></script>
<script type="text/javascript" src="js/rules.js"></script>
<script type="text/javascript" src="js/player.js"></script> -->

<script type="text/javascript" src="index.js"></script>

</head>
<body>
    
<div id="container">
    
    <div id="header">

        <h1>Eido<span>Go</span></h1>

        <p id="ownership">EidoGo is <a href="source">Open Source</a>.
            &nbsp;Maintained by <a href="http://tin.nu/">Justin Kramer</a>.</p>

        <ul id="links">
            <li><a href="/">Home</a></li>
            <li><a href="kjd">Joseki Tutor</a></li>
            <li><a href="search">Pattern Search</a></li>
            <!-- <li><a href="games">Game Archive</a></li> -->
            <li><a href="gnugo" style='padding-right: 5px'>GNU Go</a></li>
            <li><a href="gnugo;9" style='padding-left: 5px; padding-right: 5px'>9x9</a></li>
            <li><a href="gnugo;13" style='padding-left: 5px'>13x13</a></li>
            <li><a href="blank">Blank Board</a></li>
            <li><a href="upload">Upload</a></li>
            <li><a href="http://senseis.xmp.net/?EidoGo">Info</a></li>
        </ul>

    </div>

    <div id="content">
